name: agriwaste
description: Stubble burning solution

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^5.0.2
  card_settings: ^1.4.1
  cupertino_icons: ^0.1.2
  http: "^0.11.3+17"
  google_sign_in: ^3.2.1
  fluttertoast:
  flutter_svg: ^0.6.1+1
  intro_views_flutter: ^2.4.0
  shared_preferences: ^0.5.1+2
  firebase_database:
  firebase_core:
  firebase_analytics:
  firebase_storage:
  carousel_pro: ^0.0.13
  carousel_slider: ^1.3.0
  fancy_bottom_navigation: ^0.3.2
  firebase_auth: ^0.6.6
  intl:


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/email.svg
  - assets/gmail.svg
  - assets/smartphone.svg
  - assets/otp-icon.png
  - assets/success.png
  - assets/delete.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages